name: flutter_getx_template
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  # 服务端设置cookie使用
  # dio_cookie_manager: ^3.2.0
  # cookie_jar: ^4.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.4.4
  sentry_flutter: ^8.14.2
  # AES加密
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
